/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proovedor;

import Registro.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Menu.Menu;

public class InterfazProovedores extends javax.swing.JFrame {

    /**
     * Creates new form InterfazProovedores
     */
    private ArrayList<Proveedor> prov;
    public InterfazProovedores() {
        prov = new ArrayList<Proveedor>();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtSexo = new javax.swing.JTextField();
        TxtCiudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jLabelAGREGAR = new javax.swing.JLabel();
        jButtonELIMINAR = new javax.swing.JButton();
        jLabelMENU = new javax.swing.JLabel();
        jButtonMENU = new javax.swing.JButton();
        jLabelELIMINAR = new javax.swing.JLabel();
        jButtonAGREGAR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 170, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        TxtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, 30));

        TxtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel4.setText("Cedula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel5.setText("Correo Electronico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));

        TxtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 30));

        TxtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 180, 30));

        TxtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 180, 31));

        TxtSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSexoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 180, 29));

        TxtCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 179, 30));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel6.setText("Ciudad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 150, 30));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 150, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 150, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel9.setText("Telefono");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TablaDatos.setAutoCreateRowSorter(true);
        TablaDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, ""},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Telefono", "Ciudad", "Direccion", "Correo Electronico", "Sexo"
            }
        ));
        TablaDatos.setOpaque(false);
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 660, 290));

        jLabelAGREGAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAGREGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas-simbolo-negro.png"))); // NOI18N
        jLabelAGREGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAGREGARMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 60, 40));

        jButtonELIMINAR.setBackground(new java.awt.Color(0, 0, 0));
        jButtonELIMINAR.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButtonELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonELIMINAR.setText("ELIMINAR");
        jButtonELIMINAR.setBorder(null);
        jButtonELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonELIMINARActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 180, 40));

        jLabelMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        jLabelMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMENUMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 60, 40));

        jButtonMENU.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMENU.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButtonMENU.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMENU.setText("MENU");
        jButtonMENU.setBorder(null);
        jButtonMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMENUActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 180, 40));

        jLabelELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar (1).png"))); // NOI18N
        jLabelELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelELIMINARMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 60, 40));

        jButtonAGREGAR.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAGREGAR.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButtonAGREGAR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAGREGAR.setText("AGREGAR");
        jButtonAGREGAR.setBorder(null);
        jButtonAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAGREGARActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 180, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mensajero.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PROVEEDORES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 350, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoActionPerformed

    private void TxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCedulaActionPerformed

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void TxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDireccionActionPerformed

    private void TxtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSexoActionPerformed

    private void TxtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCiudadActionPerformed

    private void jLabelAGREGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAGREGARMouseClicked
        String Nom, Ape, Ciu, Sex, Dir, Cor_dir;
        int Ced, Tel;
        try {
            Nom = TxtNombre.getText();
            Ape = TxtApellido.getText();
            Ciu = TxtCiudad.getText();
            Sex = TxtSexo.getText();
            Dir = TxtDireccion.getText();
            Cor_dir = TxtCorreo.getText();
            Ced = Integer.parseInt(TxtCedula.getText());
            Tel = Integer.parseInt(TxtTelefono.getText());
            prov.add(new Proveedor(Nom, Ape, Ciu, Sex, Dir, Cor_dir, Ced, Tel));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "verifique los datos");
        }
        Limpiar();
        verDatos();
    }//GEN-LAST:event_jLabelAGREGARMouseClicked

    private void jButtonELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonELIMINARActionPerformed
        int a;
        try {
            a = TablaDatos.getSelectedRow();
            prov.remove(a);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor, escoga una fila");
        }
        verDatos();
    }//GEN-LAST:event_jButtonELIMINARActionPerformed

    private void jLabelMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMENUMouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMENUMouseClicked

    private void jButtonMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMENUActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMENUActionPerformed

    private void jLabelELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelELIMINARMouseClicked
        int a;
        try {
            a = TablaDatos.getSelectedRow();
            prov.remove(a);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor, escoga una fila");
        }
        verDatos();
    }//GEN-LAST:event_jLabelELIMINARMouseClicked

    private void jButtonAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAGREGARActionPerformed
        String Nom, Ape, Ciu, Sex, Dir, Cor_dir;
        int Ced, Tel;
        try {
            Nom = TxtNombre.getText();
            Ape = TxtApellido.getText();
            Ciu = TxtCiudad.getText();
            Sex = TxtSexo.getText();
            Dir = TxtDireccion.getText();
            Cor_dir = TxtCorreo.getText();
            Ced = Integer.parseInt(TxtCedula.getText());
            Tel = Integer.parseInt(TxtTelefono.getText());
            prov.add(new Proveedor (Nom, Ape, Ciu, Sex, Dir, Cor_dir, Ced, Tel));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "verifique los datos");
        }
        Limpiar();
        verDatos();
    }//GEN-LAST:event_jButtonAGREGARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazProovedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazProovedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazProovedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazProovedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazProovedores().setVisible(true);
            }
        });
    }

    private void Limpiar() {
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtCiudad.setText("");
        TxtSexo.setText("");
        TxtDireccion.setText("");
        TxtCorreo.setText("");
        TxtCedula.setText("");
        TxtTelefono.setText("");
    }
    private void verDatos(){
        String mat[][] = new String[prov.size()][8];
        Proveedor aux;
        for (int i=0; i<prov.size(); i++){
            aux = prov.get(i);
            mat [i][0] = aux.getNombre();
            mat [i][1] = aux.getApellido();
            mat [i][2] = Integer.toString(aux.getCedula());
            mat [i][3] = Integer.toString(aux.getTelefono());
            mat [i][4] = aux.getCiudad();
            mat [i][5] = aux.getDireccion();
            mat [i][6] = aux.getCor_dir();
            mat [i][7] = aux.getSexo();
        }
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            mat,
            new String [] {
                "Nombre", "Apellido", "Cedula", "Telefono", "Ciudad", "Direccion", "Correo Electronico", "Sexo"
            }
        ));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtCiudad;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtSexo;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton jButtonAGREGAR;
    private javax.swing.JButton jButtonELIMINAR;
    private javax.swing.JButton jButtonMENU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAGREGAR;
    private javax.swing.JLabel jLabelELIMINAR;
    private javax.swing.JLabel jLabelMENU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
        
