/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario;

import javax.swing.JOptionPane;
import Menu.Menu;
import Inventario.interfazMonitores;
import Inventario.interfazCPU_GPU;
import Inventario.interfazMouse;
import Inventario.interfazTeclado;

/**
 *
 * @author Lenovo
 */
public class InterfazInventario extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInventario
     */
    public InterfazInventario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMONITORES = new javax.swing.JLabel();
        jButtonMONITORES = new javax.swing.JButton();
        jLabelCPU_GPU = new javax.swing.JLabel();
        jButtonCPU_GPU = new javax.swing.JButton();
        jLabelMOUSE = new javax.swing.JLabel();
        jButtonMOUSE = new javax.swing.JButton();
        jLabelTECLADO = new javax.swing.JLabel();
        jButtonTECLADO = new javax.swing.JButton();
        jLabelALMACENAMIENTO = new javax.swing.JLabel();
        jButtonALMACENAMIENTO = new javax.swing.JButton();
        jLabelMEMORIAS = new javax.swing.JLabel();
        MEMORIAS = new javax.swing.JButton();
        jLabelMENU = new javax.swing.JLabel();
        jButtonMENU = new javax.swing.JButton();
        jLabelSALIR2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMONITORES.setText("jLabel1");
        jLabelMONITORES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMONITORESMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMONITORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 70, 51));

        jButtonMONITORES.setText("MONITORES");
        jButtonMONITORES.setBorder(null);
        jButtonMONITORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMONITORESActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMONITORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 51));

        jLabelCPU_GPU.setText("jLabel1");
        jLabelCPU_GPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCPU_GPUMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelCPU_GPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 70, 50));

        jButtonCPU_GPU.setText("CPU/GPU");
        jButtonCPU_GPU.setBorder(null);
        jButtonCPU_GPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCPU_GPUActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCPU_GPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, 51));

        jLabelMOUSE.setText("jLabel1");
        jLabelMOUSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMOUSEMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMOUSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 110, 80, 51));

        jButtonMOUSE.setText("MOUSE");
        jButtonMOUSE.setBorder(null);
        jButtonMOUSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMOUSEActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMOUSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 110, 51));

        jLabelTECLADO.setText("jLabel1");
        jLabelTECLADO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTECLADOMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelTECLADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 180, 80, 51));

        jButtonTECLADO.setText("TECLADO");
        jButtonTECLADO.setBorder(null);
        jButtonTECLADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTECLADOActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTECLADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 110, 50));

        jLabelALMACENAMIENTO.setText("jLabel1");
        jPanel1.add(jLabelALMACENAMIENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 250, 80, 51));

        jButtonALMACENAMIENTO.setText("STORAGE");
        jButtonALMACENAMIENTO.setBorder(null);
        jPanel1.add(jButtonALMACENAMIENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 110, 51));

        jLabelMEMORIAS.setText("jLabel1");
        jPanel1.add(jLabelMEMORIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 70, 51));

        MEMORIAS.setText("MEMORIAS");
        MEMORIAS.setBorder(null);
        MEMORIAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEMORIASActionPerformed(evt);
            }
        });
        jPanel1.add(MEMORIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 51));

        jLabelMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        jLabelMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMENUMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 50, 40));

        jButtonMENU.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMENU.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButtonMENU.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMENU.setText("MENU");
        jButtonMENU.setBorder(null);
        jButtonMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMENUActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 180, 40));

        jLabelSALIR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSALIR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarse.png"))); // NOI18N
        jLabelSALIR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSALIR2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelSALIR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 50, 40));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SALIR");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMENUMouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMENUMouseClicked

    private void jButtonMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMENUActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMENUActionPerformed

    private void jLabelSALIR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSALIR2MouseClicked
        int Dialog = JOptionPane.YES_NO_OPTION;
        int Result = JOptionPane.showConfirmDialog(null, "¿Desea salir de la pantalla?", "Exit",
                Dialog);
        if (Result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabelSALIR2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int Dialog = JOptionPane.YES_NO_OPTION;
        int Result = JOptionPane.showConfirmDialog(null, "¿Desea salir de la pantalla?", "Exit",
                Dialog);
        if (Result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonMONITORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMONITORESActionPerformed
        interfazMonitores interfazMonitores = new interfazMonitores();
        interfazMonitores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMONITORESActionPerformed

    private void jButtonCPU_GPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPU_GPUActionPerformed
        interfazCPU_GPU interfazCpu_Gpu = new interfazCPU_GPU();
        interfazCpu_Gpu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCPU_GPUActionPerformed

    private void jLabelMONITORESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMONITORESMouseClicked
        interfazMonitores interfazMonitores = new interfazMonitores();
        interfazMonitores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMONITORESMouseClicked

    private void jLabelCPU_GPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCPU_GPUMouseClicked
        interfazCPU_GPU interfazCpu_Gpu = new interfazCPU_GPU();
        interfazCpu_Gpu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCPU_GPUMouseClicked

    private void jButtonMOUSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMOUSEActionPerformed
        interfazMouse interfazMouse = new interfazMouse();
        interfazMouse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMOUSEActionPerformed

    private void jLabelMOUSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMOUSEMouseClicked
        interfazMouse interfazMouse = new interfazMouse();
        interfazMouse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelMOUSEMouseClicked

    private void MEMORIASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEMORIASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MEMORIASActionPerformed

    private void jButtonTECLADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTECLADOActionPerformed
        interfazTeclado interfazTeclado = new interfazTeclado();
        interfazTeclado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTECLADOActionPerformed

    private void jLabelTECLADOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTECLADOMouseClicked
        interfazTeclado interfazTeclado = new interfazTeclado();
        interfazTeclado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelTECLADOMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MEMORIAS;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonALMACENAMIENTO;
    private javax.swing.JButton jButtonCPU_GPU;
    private javax.swing.JButton jButtonMENU;
    private javax.swing.JButton jButtonMONITORES;
    private javax.swing.JButton jButtonMOUSE;
    private javax.swing.JButton jButtonTECLADO;
    private javax.swing.JLabel jLabelALMACENAMIENTO;
    private javax.swing.JLabel jLabelCPU_GPU;
    private javax.swing.JLabel jLabelMEMORIAS;
    private javax.swing.JLabel jLabelMENU;
    private javax.swing.JLabel jLabelMONITORES;
    private javax.swing.JLabel jLabelMOUSE;
    private javax.swing.JLabel jLabelSALIR2;
    private javax.swing.JLabel jLabelTECLADO;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
